### ISSUE TITLE
Migrate from OpenNLP to the latest version of similar lib with POS tags

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/lints#129]
Check this one: https://github.com/objectionary/lints/pull/126#issuecomment-2531215735

**Comment by h1alexbel** [comment]
@yegor256 assign me, please

**Comment by yegor256** [comment]
@h1alexbel go ahead

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#135](https://github.com/objectionary/lints/issues/135) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.24`

**Comment by 0pdd** [comment]
@h1alexbel the only puzzle [#135](https://github.com/objectionary/lints/issues/135) is solved here.
