### ISSUE TITLE
benchmark is missing

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#134]
Currently, we don't have a benchmark of our linting features. Let's create one. It should calculate how much it takes to lint a small XMIR, a large, an X-large, an XXL, etc. We can publish this information in README, similar to how we publish it here: https://github.com/objectionary/hone-maven-plugin/blob/master/.github/workflows/benchmark.yml

**Comment by yegor256** [comment]
@h1alexbel please, help

**Comment by h1alexbel** [comment]
@yegor256 assign me

**Comment by yegor256** [comment]
@h1alexbel go ahead

**Comment by h1alexbel** [comment]
@yegor256 @volodya-lombrozo could you provide some large XMIRs as the source for benchmarking?

**Comment by yegor256** [comment]
@h1alexbel it's better to generate such an XMIR, instead of keeping it in the project. You can see how we generate it here: https://github.com/objectionary/hone-maven-plugin/blob/master/src/test/java/org/eolang/hone/OptimizeMojoTest.java#L224

**Comment by h1alexbel** [comment]
@yegor256 as far I understand, we need to generate XMIR from EO, not Java, right?

**Comment by yegor256** [comment]
@h1alexbel it's hard to build such a large EO file as of now. We don't have a generator of random EO programs yet. That's why we can use large `.java/.class` files, convertible to EO via jeo-maven-plugin.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#143](https://github.com/objectionary/lints/issues/143), [#144](https://github.com/objectionary/lints/issues/144) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#143](https://github.com/objectionary/lints/issues/143), [#190](https://github.com/objectionary/lints/issues/190) are still not solved; solved: [#144](https://github.com/objectionary/lints/issues/144).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#190](https://github.com/objectionary/lints/issues/190), [#470](https://github.com/objectionary/lints/issues/470) are still not solved; solved: [#143](https://github.com/objectionary/lints/issues/143), [#144](https://github.com/objectionary/lints/issues/144).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#190](https://github.com/objectionary/lints/issues/190) is still not solved; solved: [#143](https://github.com/objectionary/lints/issues/143), [#144](https://github.com/objectionary/lints/issues/144), [#470](https://github.com/objectionary/lints/issues/470).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#509](https://github.com/objectionary/lints/issues/509) is still not solved; solved: [#143](https://github.com/objectionary/lints/issues/143), [#144](https://github.com/objectionary/lints/issues/144), [#190](https://github.com/objectionary/lints/issues/190), [#470](https://github.com/objectionary/lints/issues/470).

**Comment by 0pdd** [comment]
@yegor256 all 5 puzzles are solved here: [#143](https://github.com/objectionary/lints/issues/143), [#144](https://github.com/objectionary/lints/issues/144), [#190](https://github.com/objectionary/lints/issues/190), [#470](https://github.com/objectionary/lints/issues/470), [#509](https://github.com/objectionary/lints/issues/509).
