### ISSUE TITLE
The `AsciiOnly` lint doesn't show the abusive character

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#14]
When a comment has a wrong character, `AsciiOnly` simply claims that such a comment is broken, but doesn't say in what line and what is the character. This makes it hard to find and fix the problem. Let's make the output of `AsciiOnly` more detailed.

**Comment by h1alexbel** [comment]
@yegor256 let me fix this

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#34](https://github.com/objectionary/lints/issues/34) is still not solved.
