### ISSUE TITLE
ProgramTest.java:59-64: Capture all the lint timings in...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/lints#144]
The puzzle `134-6deff79b` from #134 has to be resolved: 

https://github.com/objectionary/lints/blob/ec352ec8a9402693173483008c87a0dbf2dd6028/src/test/java/org/eolang/lints/ProgramTest.java#L59-L64

The puzzle was created by @yegor256 on 13-Dec-24. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
@yegor256 assign me, please

**Comment by yegor256** [comment]
@h1alexbel go ahead

**Comment by 0pdd** [comment]
@0pdd the puzzle [#190](https://github.com/objectionary/lints/issues/190) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#509](https://github.com/objectionary/lints/issues/509) is still not solved; solved: [#190](https://github.com/objectionary/lints/issues/190).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#190](https://github.com/objectionary/lints/issues/190), [#509](https://github.com/objectionary/lints/issues/509).
