### ISSUE TITLE
The `+package` meta must be mandatory

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#17]
If the `+package` is not present, let's issue a warning. I believe, we will need a new lint for this.

**Comment by h1alexbel** [comment]
@yegor256 `mandatory-package-meta` lint already checks presence of `+package` meta:

https://github.com/objectionary/lints/blob/d9e25cf92ecc5226962b843b66d9378f4eb450c8/src/main/resources/org/eolang/lints/metas/mandatory-package-meta.xsl#L29

test pack:

https://github.com/objectionary/lints/blob/d9e25cf92ecc5226962b843b66d9378f4eb450c8/src/test/resources/org/eolang/lints/eo-packs/catches-mandatory-package-meta.yaml#L23-L36

can we close this issue? WDYT?

**Comment by yegor256** [comment]
@h1alexbel you are right, thanks!
