### ISSUE TITLE
The `+version` meta must be mandatory

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#18]
If the `+version` is not present, let's issue a warning. I believe, we will need a new lint for this.

**Comment by h1alexbel** [comment]
@yegor256 `mandatory-version-meta.xsl` checks that:

https://github.com/objectionary/lints/blob/c2739ff458ca1457cd0505de3fcd262a924f9e4f/src/main/resources/org/eolang/lints/metas/mandatory-version-meta.xsl#L29

test pack:

https://github.com/objectionary/lints/blob/c2739ff458ca1457cd0505de3fcd262a924f9e4f/src/test/resources/org/eolang/lints/eo-packs/catches-mandatory-version-meta.yaml#L23-L36

can we close this issue? WDYT?

**Comment by yegor256** [comment]
@h1alexbel right, thanks!
