### ISSUE TITLE
Refactor lints for unique metas

### ISSUE THREAD

**Issue by h1alexbel** [objectionary/lints#186]
Currently, we have 4 very similar lints:

* `version-duplicate.xsl`
* `architect-duplicate.xsl`
* `home-duplicate.xsl`
* `package-duplicate.xsl`

Let's merge them into one lint: `unique-metas.xsl` that will check the following metas are unique: `+version`, `+architect`, `+home`, `+package`.

**Comment by yegor256** [comment]
@h1alexbel fully agree, let's do this

**Comment by h1alexbel** [comment]
@yegor256 assign me, please
