### ISSUE TITLE
`Lint.motive()`

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#19]
Let's add a new method to the `Lint` class: `.motive()`. It will return a piece of text (maybe a few paragraphs) in Markdown, explaining why this linter exists and how does it improve the code. Later, we will use this text to generate documentation and publish in the `README.md` (automatically, on every CI build).

**Comment by h1alexbel** [comment]
@yegor256 assign me please

**Comment by yegor256** [comment]
@h1alexbel go ahead, please

**Comment by 0pdd** [comment]
@yegor256 5 puzzles [#41](https://github.com/objectionary/lints/issues/41), [#42](https://github.com/objectionary/lints/issues/42), [#43](https://github.com/objectionary/lints/issues/43), [#44](https://github.com/objectionary/lints/issues/44), [#45](https://github.com/objectionary/lints/issues/45) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 4 puzzles [#41](https://github.com/objectionary/lints/issues/41), [#42](https://github.com/objectionary/lints/issues/42), [#43](https://github.com/objectionary/lints/issues/43), [#45](https://github.com/objectionary/lints/issues/45) are still not solved; solved: [#44](https://github.com/objectionary/lints/issues/44).

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#41](https://github.com/objectionary/lints/issues/41), [#42](https://github.com/objectionary/lints/issues/42), [#43](https://github.com/objectionary/lints/issues/43) are still not solved; solved: [#44](https://github.com/objectionary/lints/issues/44), [#45](https://github.com/objectionary/lints/issues/45).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#41](https://github.com/objectionary/lints/issues/41), [#43](https://github.com/objectionary/lints/issues/43) are still not solved; solved: [#42](https://github.com/objectionary/lints/issues/42), [#44](https://github.com/objectionary/lints/issues/44), [#45](https://github.com/objectionary/lints/issues/45).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#43](https://github.com/objectionary/lints/issues/43) is still not solved; solved: [#41](https://github.com/objectionary/lints/issues/41), [#42](https://github.com/objectionary/lints/issues/42), [#44](https://github.com/objectionary/lints/issues/44), [#45](https://github.com/objectionary/lints/issues/45).

**Comment by 0pdd** [comment]
@yegor256 all 5 puzzles are solved here: [#41](https://github.com/objectionary/lints/issues/41), [#42](https://github.com/objectionary/lints/issues/42), [#43](https://github.com/objectionary/lints/issues/43), [#44](https://github.com/objectionary/lints/issues/44), [#45](https://github.com/objectionary/lints/issues/45).
