### ISSUE TITLE
Some metas must be unique

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#23]
Consider this code:

```
+version 0.1.2
+version 1.4.5

[] > foo
```

Here, the `+version` is used twice, which is wrong. Let's make sure the following metas are unique (used only once):

  * `+version`
  * `+architect`
  * `+home`
  * `+package`

**Comment by h1alexbel** [comment]
@yegor256 now, we miss only `architect-duplicate` lint (unique checks for other 
`+version`, `+home`, `+package` metas are implemented). Please assign me

**Comment by yegor256** [comment]
@h1alexbel maybe it's better to put them all together into one lint?

**Comment by h1alexbel** [comment]
@yegor256 yes, thought about that. Maybe let's merge #177 first, we will have all the test cases we need, and then refactor 
all duplicated lints into one? WDYT?
