### ISSUE TITLE
atoms must not have data

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#46]
This XMIR should be illegal:

```
<o atom="Fun">
  <o name="foo"/>
  00-01-02
</o>
```

A `<o/>` element may not have any `text()` inside, if `@atom` attribute is present. Let's issue a `critical` error in this case.

**Comment by yegor256** [comment]
@maxonfjvipon am I right?

**Comment by h1alexbel** [comment]
@yegor256 I'm in
