### ISSUE TITLE
the formatting of the `+rt jvm` meta is not checked

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#51]
Currently, this is possible:

```
+rt jvm hello, world!
```

This doesn't make sense, since the second part of this meta must be in this format only:

```
+rt jvm org.eolang:eo-runtime:0.0.0
```

Here, Maven groupId goes first, artifactId next, and version last. Let's add a linter for this.

BTW, the format of the second part is different, if the first part is `node` (just name + version):

```
eo2js-runtime:0.0.0
```

**Comment by h1alexbel** [comment]
@yegor256 assign me please

**Comment by yegor256** [comment]
@h1alexbel go ahead
