### ISSUE TITLE
attach version of the library to every `Defect`

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#60]
When error is reported, the version of the linter is not known. Let's add method `version` to the `Defect` interface, making it return the current version of the JAR.

**Comment by h1alexbel** [comment]
@yegor256 assign me, please

**Comment by yegor256** [comment]
@h1alexbel go ahead!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.12`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.13`

**Comment by h1alexbel** [comment]
@yegor256 should we close this one? looks like jt was released
