### ISSUE TITLE
Can't introduce base for void attribute

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/lints#76]
I'm trying to implement this feature: https://github.com/objectionary/eo/issues/3529.
It [requires](https://github.com/objectionary/eo/issues/3529#issuecomment-2495959118) us to put `∅` as base to void attributes.
EO:
```
[x] > main
```

XML:
```xml
<objects>
  <o name="main">
    <o base="∅" name="x"/>
  </o>
</objects>
```

While implementing I'm getting tests failed on verification step with next error: `The object "∅" is not defined anywhere (unknown-name)`

I think an exceptional case must be added to the `unkhown-name` check.

**Comment by maxonfjvipon** [comment]
@yegor256 WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon yes, definitely

**Comment by maxonfjvipon** [comment]
@yegor256 please assign me

**Comment by yegor256** [comment]
@maxonfjvipon go ahead

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.14`
